import { publicAssetUrl } from '@/modules/shared/lib/utils';

// Icon keys that are dark-filled SVGs and need `dark:invert` in dark mode.
export const darkInvertIconKeys = new Set([
    'bem',
    'express',
    'fastify',
    'github',
    'markdown',
    'prisma',
    'shadcn',
]);

const rawIconUrls: Record<string, string> = {
    anaconda: '/skill-icons/anaconda.svg',
    angular: '/skill-icons/angular.svg',
    angularjs: '/skill-icons/angularjs.svg',
    antdesign: '/skill-icons/ant-design.svg',
    apache: '/skill-icons/apache.svg',
    apollo: '/skill-icons/apollo.svg',
    appveyor: '/skill-icons/appveyor.svg',
    asana: '/skill-icons/asana.svg',
    aws: '/skill-icons/aws.svg',
    backbone: '/skill-icons/backbone.svg',
    bem: '/skill-icons/bem.svg',
    bootstrap: '/skill-icons/bootstrap.svg',
    bun: '/skill-icons/bun.svg',
    chai: '/skill-icons/chai.svg',
    circleci: '/skill-icons/circle-ci.svg',
    claudecode: '/skill-icons/claude-code.svg',
    coffeescript: '/skill-icons/coffeescript.svg',
    csharp: '/skill-icons/csharp.svg',
    css3: '/skill-icons/css3.svg',
    cssmodules: '/skill-icons/css3.svg',
    cursor: '/skill-icons/cursor.svg',
    cypress: '/skill-icons/cypress.svg',
    datefns: '/skill-icons/date-fns.svg',
    dbeaver: '/skill-icons/dbeaver.svg',
    django: '/skill-icons/django.svg',
    docker: '/skill-icons/docker.svg',
    drizzle: '/skill-icons/drizzle.svg',
    elasticsearch: '/skill-icons/elasticsearch.svg',
    esbuild: '/skill-icons/esbuild.svg',
    enzyme: '/skill-icons/not-available.svg',
    eslint: '/skill-icons/eslint.svg',
    expo: '/skill-icons/expo.svg',
    express: '/skill-icons/express.svg',
    fastify: '/skill-icons/fastify.svg',
    figma: '/skill-icons/figma.svg',
    git: '/skill-icons/git.svg',
    github: '/skill-icons/github.svg',
    githubactions: '/skill-icons/githubactions.svg',
    githubcopilot: '/skill-icons/github-copilot.svg',
    gitlab: '/skill-icons/gitlab.svg',
    gmail: '/skill-icons/gmail.svg',
    grafana: '/skill-icons/grafana.svg',
    graphql: '/skill-icons/graphql.svg',
    gulp: '/skill-icons/gulp.svg',
    hono: '/skill-icons/hono.svg',
    html5: '/skill-icons/html5.svg',
    html5canvas: '/skill-icons/html5.svg',
    jasmine: '/skill-icons/jasmine.svg',
    javascript: '/skill-icons/javascript.svg',
    jenkins: '/skill-icons/jenkins.svg',
    jest: '/skill-icons/jest.svg',
    jira: '/skill-icons/jira.svg',
    jotai: '/skill-icons/not-available.svg',
    jquery: '/skill-icons/jquery.svg',
    kubernetes: '/skill-icons/kubernetes.svg',
    kysely: '/skill-icons/kysely.svg',
    less: '/skill-icons/less.svg',
    linkedin: '/skill-icons/linkedin.svg',
    lodash: '/skill-icons/lodash.svg',
    lua: '/skill-icons/lua.svg',
    markdown: '/skill-icons/markdown.svg',
    materialui: '/skill-icons/material-ui.svg',
    matplotlib: '/skill-icons/matplotlib.svg',
    mobx: '/skill-icons/mobx.svg',
    mocha: '/skill-icons/mocha.svg',
    mongodb: '/skill-icons/mongodb.svg',
    mongoose: '/skill-icons/mongoose.svg',
    moment: '/skill-icons/moment.svg',
    mysql: '/skill-icons/mysql.svg',
    neon: '/skill-icons/neon.svg',
    nestjs: '/skill-icons/nestjs.svg',
    netlify: '/skill-icons/netlify.svg',
    nextjs: '/skill-icons/nextjs.svg',
    nginx: '/skill-icons/nginx.svg',
    nodejs: '/skill-icons/nodejs.svg',
    notAvailable: '/skill-icons/not-available.svg',
    npm: '/skill-icons/npm.svg',
    numpy: '/skill-icons/numpy.svg',
    oxfmt: '/skill-icons/oxc.svg',
    oxlint: '/skill-icons/oxc.svg',
    pandas: '/skill-icons/pandas.svg',
    php: '/skill-icons/php.svg',
    playwright: '/skill-icons/playwright.svg',
    pnpm: '/skill-icons/pnpm.svg',
    postcss: '/skill-icons/postcss.svg',
    postgresql: '/skill-icons/postgresql.svg',
    prettier: '/skill-icons/prettier.svg',
    prisma: '/skill-icons/prisma.svg',
    prometheus: '/skill-icons/prometheus.svg',
    protractor: '/skill-icons/protractor.svg',
    puppeteer: '/skill-icons/puppeteer.svg',
    python: '/skill-icons/python.svg',
    rabbitmq: '/skill-icons/rabbitmq.svg',
    react: '/skill-icons/react.svg',
    reacthookform: '/skill-icons/react-hook-form.svg',
    reactrouter: '/skill-icons/react-router.svg',
    reactivex: '/skill-icons/reactivex.svg',
    recharts: '/skill-icons/not-available.svg',
    redis: '/skill-icons/redis.svg',
    redux: '/skill-icons/redux.svg',
    rollup: '/skill-icons/rollup.svg',
    rspec: '/skill-icons/rspec.svg',
    ruby: '/skill-icons/ruby.svg',
    rubyonrails: '/skill-icons/rubyonrails.svg',
    rxjs: '/skill-icons/reactivex.svg',
    sass: '/skill-icons/sass.svg',
    scikitlearn: '/skill-icons/scikit-learn.svg',
    seaborn: '/skill-icons/seaborn.svg',
    scss: '/skill-icons/sass.svg',
    selenium: '/skill-icons/selenium.svg',
    sequelize: '/skill-icons/sequelize.svg',
    shadcn: '/skill-icons/shadcn.svg',
    sinon: '/skill-icons/not-available.svg',
    sketch: '/skill-icons/sketch.svg',
    socketio: '/skill-icons/socket-io.svg',
    spinnaker: '/skill-icons/spinnaker.svg',
    sqlite: '/skill-icons/sqlite.svg',
    storybook: '/skill-icons/storybook.svg',
    stripe: '/skill-icons/stripe.svg',
    styledcomponents: '/skill-icons/styled-components.svg',
    stylelint: '/skill-icons/stylelint.svg',
    stylus: '/skill-icons/stylus.svg',
    supabase: '/skill-icons/supabase.svg',
    tailwindcss: '/skill-icons/tailwindcss.svg',
    tanstackform: '/skill-icons/tanstack.svg',
    tanstackquery: '/skill-icons/tanstack-query.svg',
    tanstackrouter: '/skill-icons/tanstack.svg',
    testinglibrary: '/skill-icons/testing-library.svg',
    tex: '/skill-icons/tex.svg',
    travisci: '/skill-icons/travis-ci.svg',
    trello: '/skill-icons/trello.svg',
    turborepo: '/skill-icons/turborepo.svg',
    typeorm: '/skill-icons/typeorm.svg',
    typescript: '/skill-icons/typescript.svg',
    upstash: '/skill-icons/upstash.svg',
    vercel: '/skill-icons/vercel.svg',
    vite: '/skill-icons/vite.svg',
    vitest: '/skill-icons/vitest.svg',
    waiaria: '/skill-icons/wai-aria.svg',
    webpack: '/skill-icons/webpack.svg',
    yarn: '/skill-icons/yarn.svg',
    zeplin: '/skill-icons/zeplin.svg',
    zod: '/skill-icons/zod.svg',
    zustand: '/skill-icons/not-available.svg',
};

export const iconUrls: Record<string, string> = Object.fromEntries(
    Object.entries(rawIconUrls).map(([k, v]) => [k, publicAssetUrl(v)]),
);
