import type { TranslationKey } from '@/modules/shared/i18n/translator';
import { iconUrls } from './icon-urls';

export interface ProjectTechItem {
    name: string;
    icon?: string;
}

const TECH = {
    claudecode: { name: 'Claude Code', icon: iconUrls['claudecode'] },
    cursor: { name: 'Cursor', icon: iconUrls['cursor'] },
    html5: { name: 'HTML5', icon: iconUrls['html5'] },
    css3: { name: 'CSS3', icon: iconUrls['css3'] },
    react: { name: 'React', icon: iconUrls['react'] },
    typescript: { name: 'TypeScript', icon: iconUrls['typescript'] },
    tailwindcss: { name: 'Tailwind CSS', icon: iconUrls['tailwindcss'] },
    vite: { name: 'Vite', icon: iconUrls['vite'] },
    vitest: { name: 'Vitest', icon: iconUrls['vitest'] },
    playwright: { name: 'Playwright', icon: iconUrls['playwright'] },
    eslint: { name: 'ESLint', icon: iconUrls['eslint'] },
    prettier: { name: 'Prettier', icon: iconUrls['prettier'] },
    pnpm: { name: 'pnpm', icon: iconUrls['pnpm'] },
    redux: { name: 'Redux', icon: iconUrls['redux'] },
    html5canvas: { name: 'HTML5 Canvas', icon: iconUrls['html5canvas'] },
    angularjs: { name: 'AngularJS', icon: iconUrls['angularjs'] },
    javascript: { name: 'JavaScript', icon: iconUrls['javascript'] },
    bootstrap: { name: 'Bootstrap', icon: iconUrls['bootstrap'] },
    webpack: { name: 'Webpack', icon: iconUrls['webpack'] },
    oxlint: { name: 'Oxlint', icon: iconUrls['oxlint'] },
    oxfmt: { name: 'Oxfmt', icon: iconUrls['oxfmt'] },
    stylelint: { name: 'Stylelint', icon: iconUrls['stylelint'] },
    jquery: { name: 'jQuery', icon: iconUrls['jquery'] },
    less: { name: 'Less', icon: iconUrls['less'] },
    postcss: { name: 'PostCSS', icon: iconUrls['postcss'] },
    zod: { name: 'Zod', icon: iconUrls['zod'] },
    testinglibrary: { name: 'Testing Library', icon: iconUrls['testinglibrary'] },
} satisfies Record<string, ProjectTechItem>;

export interface Project {
    id: string;
    titleKey: TranslationKey;
    descriptionKey: TranslationKey;
    image: string;
    techstack: ProjectTechItem[];
    demoUrl: string;
    repoUrl: string;
}

export const projectsData: Project[] = [
    {
        id: 'portfolioWebsite',
        titleKey: 'portfolio.projects.items.portfolioWebsite.title',
        descriptionKey: 'portfolio.projects.items.portfolioWebsite.description',
        image: '/projects/my-portfolio.png',
        techstack: [
            TECH.claudecode,
            TECH.cursor,
            TECH.html5,
            TECH.css3,
            TECH.react,
            TECH.typescript,
            TECH.tailwindcss,
            TECH.vite,
            TECH.vitest,
            TECH.playwright,
            TECH.stylelint,
            TECH.oxlint,
            TECH.oxfmt,
            TECH.testinglibrary,
            TECH.pnpm,
        ],
        demoUrl: 'https://everget.github.io/my-portfolio-website/',
        repoUrl: 'https://github.com/everget/my-portfolio-website',
    },
    {
        id: 'pineScriptCheatsheet',
        titleKey: 'portfolio.projects.items.pineScriptCheatsheet.title',
        descriptionKey: 'portfolio.projects.items.pineScriptCheatsheet.description',
        image: '/projects/pinescript-cheatsheet.png',
        techstack: [
            TECH.claudecode,
            TECH.cursor,
            TECH.html5,
            TECH.css3,
            TECH.react,
            TECH.typescript,
            TECH.tailwindcss,
            TECH.vite,
            TECH.vitest,
            TECH.playwright,
            TECH.stylelint,
            TECH.eslint,
            TECH.prettier,
            TECH.testinglibrary,
            TECH.pnpm,
        ],
        demoUrl: 'https://everget.github.io/pinescript-cheatsheet/',
        repoUrl: 'https://github.com/everget/pinescript-cheatsheet',
    },
    {
        id: 'calculator',
        titleKey: 'portfolio.projects.items.calculator.title',
        descriptionKey: 'portfolio.projects.items.calculator.description',
        image: '/projects/calculator.png',
        techstack: [
            TECH.claudecode,
            TECH.cursor,
            TECH.html5,
            TECH.css3,
            TECH.typescript,
            TECH.vite,
            TECH.vitest,
            TECH.playwright,
            TECH.eslint,
            TECH.prettier,
            TECH.testinglibrary,
            TECH.pnpm,
        ],
        demoUrl: 'https://everget.github.io/calculator/',
        repoUrl: 'https://github.com/everget/calculator',
    },
    {
        id: 'todoList',
        titleKey: 'portfolio.projects.items.todoList.title',
        descriptionKey: 'portfolio.projects.items.todoList.description',
        image: '/projects/todolist.png',
        techstack: [
            TECH.claudecode,
            TECH.cursor,
            TECH.html5,
            TECH.css3,
            TECH.react,
            TECH.typescript,
            TECH.tailwindcss,
            TECH.redux,
            TECH.zod,
            TECH.vite,
            TECH.vitest,
            TECH.playwright,
            TECH.oxlint,
            TECH.oxfmt,
            TECH.testinglibrary,
            TECH.pnpm,
        ],
        demoUrl: 'https://everget.github.io/todolist-app/',
        repoUrl: 'https://github.com/everget/todolist-app',
    },
    {
        id: 'spaceInvaders',
        titleKey: 'portfolio.projects.items.spaceInvaders.title',
        descriptionKey: 'portfolio.projects.items.spaceInvaders.description',
        image: '/projects/space-invaders.webp',
        techstack: [
            TECH.html5,
            TECH.css3,
            TECH.typescript,
            TECH.html5canvas,
            TECH.vite,
            TECH.vitest,
            TECH.eslint,
            TECH.prettier,
            TECH.pnpm,
        ],
        demoUrl: 'https://everget.github.io/space-invaders/',
        repoUrl: 'https://github.com/everget/space-invaders',
    },
    {
        id: 'securitiesPortfolio',
        titleKey: 'portfolio.projects.items.securitiesPortfolio.title',
        descriptionKey: 'portfolio.projects.items.securitiesPortfolio.description',
        image: '/projects/securities-portfolio-calculator.webp',
        techstack: [
            TECH.html5,
            TECH.css3,
            TECH.angularjs,
            TECH.javascript,
            TECH.bootstrap,
            TECH.webpack,
            TECH.eslint,
            TECH.prettier,
            TECH.pnpm,
        ],
        demoUrl: 'https://everget.github.io/securities-portfolio-app/',
        repoUrl: 'https://github.com/everget/securities-portfolio-app',
    },
    {
        id: 'simpleBookStorage',
        titleKey: 'portfolio.projects.items.simpleBookStorage.title',
        descriptionKey: 'portfolio.projects.items.simpleBookStorage.description',
        image: '/projects/simple-book-storage.png',
        techstack: [
            TECH.html5,
            TECH.css3,
            TECH.jquery,
            TECH.bootstrap,
            TECH.less,
            TECH.postcss,
            TECH.vite,
            TECH.eslint,
            TECH.prettier,
            TECH.pnpm,
        ],
        demoUrl: 'https://everget.github.io/simple-book-storage/',
        repoUrl: 'https://github.com/everget/simple-book-storage',
    },
];
