export interface PortfolioSkillItem {
    name: string;
    // Key into iconUrls. Undefined = concept/principle with no icon.
    iconKey?: string;
    // External link for the skill badge.
    link?: string;
}

export interface PortfolioSkillCategory {
    key: string;
    translationKey: string;
    skills: PortfolioSkillItem[];
}

export const SKILL_CATEGORIES: PortfolioSkillCategory[] = [
    {
        key: 'languages',
        translationKey: 'portfolio.skills.categories.languages',
        skills: [
            { name: 'HTML5', iconKey: 'html5' },
            { name: 'CSS3', iconKey: 'css3' },
            { name: 'JavaScript', iconKey: 'javascript' },
            { name: 'TypeScript', iconKey: 'typescript' },
            { name: 'CoffeeScript', iconKey: 'coffeescript' },
            { name: 'Python', iconKey: 'python' },
            { name: 'Ruby', iconKey: 'ruby' },
            { name: 'Lua', iconKey: 'lua' },
            { name: 'PHP', iconKey: 'php' },
            { name: 'CSharp', iconKey: 'csharp' },
            { name: 'TeX', iconKey: 'tex' },
        ],
    },
    {
        key: 'frontend',
        translationKey: 'portfolio.skills.categories.frontend',
        skills: [
            { name: 'FSD', link: 'https://feature-sliced.design/' },
            { name: 'Canvas', iconKey: 'html5canvas' },
            {
                name: 'WAI-ARIA',
                iconKey: 'waiaria',
                link: 'https://en.wikipedia.org/wiki/WAI-ARIA',
            },
            {
                name: 'BEM',
                iconKey: 'bem',
                link: 'https://en.bem.info/methodology/css/',
            },
            { name: 'LESS', iconKey: 'less' },
            { name: 'SCSS', iconKey: 'scss' },
            {
                name: 'CSS Modules',
                iconKey: 'cssmodules',
                link: 'https://github.com/css-modules/css-modules',
            },
            { name: 'PostCSS', iconKey: 'postcss' },
            { name: 'Bootstrap', iconKey: 'bootstrap' },
            { name: 'Tailwind CSS', iconKey: 'tailwindcss' },
            { name: 'Styled Components', iconKey: 'styledcomponents' },
            {
                name: 'MUI',
                iconKey: 'materialui',
                link: 'https://mui.com/material-ui/',
            },
            { name: 'shadcn/ui', iconKey: 'shadcn' },
            { name: 'Ant Design', iconKey: 'antdesign' },
            { name: 'Storybook', iconKey: 'storybook' },
            { name: 'jQuery', iconKey: 'jquery' },
            { name: 'Backbone', iconKey: 'backbone' },
            { name: 'Angular', iconKey: 'angular' },
            { name: 'React', iconKey: 'react' },
            { name: 'Expo', iconKey: 'expo' },
            { name: 'Redux', iconKey: 'redux' },
            { name: 'MobX', iconKey: 'mobx' },
            { name: 'Zustand', iconKey: 'zustand' },
            { name: 'Jotai', iconKey: 'jotai', link: 'https://jotai.org/' },
            { name: 'TanStack Query', iconKey: 'tanstackquery' },
            { name: 'TanStack Router', iconKey: 'tanstackrouter' },
            { name: 'React Router', iconKey: 'reactrouter' },
            { name: 'TanStack Form', iconKey: 'tanstackform' },
            { name: 'React Hook Form', iconKey: 'reacthookform' },
            { name: 'RxJS', iconKey: 'rxjs' },
            { name: 'Recharts', iconKey: 'recharts' },
            { name: 'Moment', iconKey: 'moment' },
            { name: 'date-fns', iconKey: 'datefns' },
            { name: 'Figma', iconKey: 'figma' },
            { name: 'Zeplin', iconKey: 'zeplin' },
            { name: 'Sketch', iconKey: 'sketch' },
        ],
    },
    {
        key: 'backend',
        translationKey: 'portfolio.skills.categories.backend',
        skills: [
            { name: 'BFF', link: 'https://bff-patterns.com/' },
            { name: 'Ruby on Rails', iconKey: 'rubyonrails' },
            { name: 'Node.js', iconKey: 'nodejs' },
            { name: 'Express', iconKey: 'express' },
            { name: 'Next.js', iconKey: 'nextjs' },
            { name: 'Fastify', iconKey: 'fastify' },
            { name: 'Hono', iconKey: 'hono' },
            { name: 'NestJS', iconKey: 'nestjs' },
            { name: 'Django', iconKey: 'django' },
            { name: 'socket.io', iconKey: 'socketio' },
            { name: 'GraphQL', iconKey: 'graphql' },
            { name: 'Apollo', iconKey: 'apollo' },
            { name: 'RabbitMQ', iconKey: 'rabbitmq' },
            { name: 'Nginx', iconKey: 'nginx' },
            { name: 'Apache', iconKey: 'apache' },
            { name: 'Mongoose', iconKey: 'mongoose' },
            { name: 'TypeORM', iconKey: 'typeorm' },
            { name: 'Sequelize', iconKey: 'sequelize' },
            { name: 'Prisma', iconKey: 'prisma' },
            { name: 'Drizzle', iconKey: 'drizzle' },
            { name: 'Kysely', iconKey: 'kysely', link: 'https://kysely.dev/' },
            { name: 'MySQL', iconKey: 'mysql' },
            { name: 'PostgreSQL', iconKey: 'postgresql' },
            { name: 'Neon', iconKey: 'neon' },
            { name: 'SQLite', iconKey: 'sqlite' },
            { name: 'MongoDB', iconKey: 'mongodb' },
            { name: 'Redis', iconKey: 'redis' },
            { name: 'Elasticsearch', iconKey: 'elasticsearch' },
            { name: 'Upstash', iconKey: 'upstash' },
            { name: 'Netlify', iconKey: 'netlify' },
            { name: 'Vercel', iconKey: 'vercel' },
        ],
    },
    {
        key: 'testing',
        translationKey: 'portfolio.skills.categories.testing',
        skills: [
            { name: 'TDD', link: 'https://en.wikipedia.org/wiki/Test-driven_development' },
            { name: 'BDD', link: 'https://en.wikipedia.org/wiki/Behavior-driven_development' },
            { name: 'Mocha', iconKey: 'mocha' },
            { name: 'Chai', iconKey: 'chai' },
            { name: 'Sinon', iconKey: 'sinon' },
            { name: 'Jasmine', iconKey: 'jasmine' },
            { name: 'Jest', iconKey: 'jest' },
            { name: 'Vitest', iconKey: 'vitest' },
            {
                name: 'Enzyme',
                iconKey: 'enzyme',
                link: 'https://enzymejs.github.io/enzyme/',
            },
            { name: 'Testing Library', iconKey: 'testinglibrary' },
            { name: 'RSpec', iconKey: 'rspec' },
            {
                name: 'Protractor',
                iconKey: 'protractor',
                link: 'https://www.protractortest.org/#/',
            },
            { name: 'Selenium', iconKey: 'selenium' },
            { name: 'Puppeteer', iconKey: 'puppeteer' },
            { name: 'Cypress', iconKey: 'cypress' },
            { name: 'Playwright', iconKey: 'playwright' },
        ],
    },
    {
        key: 'cicd',
        translationKey: 'portfolio.skills.categories.cicd',
        skills: [
            { name: 'DevOps', link: 'https://en.wikipedia.org/wiki/DevOps' },
            { name: 'Git', iconKey: 'git' },
            {
                name: 'GitHub Flow',
                iconKey: 'github',
                link: 'https://docs.github.com/en/get-started/using-github/github-flow',
            },
            { name: 'GitHub Actions', iconKey: 'githubactions' },
            { name: 'GitLab CI', iconKey: 'gitlab' },
            { name: 'Travis CI', iconKey: 'travisci' },
            { name: 'CircleCI', iconKey: 'circleci' },
            { name: 'AppVeyor', iconKey: 'appveyor' },
            { name: 'Docker', iconKey: 'docker' },
            { name: 'Kubernetes', iconKey: 'kubernetes' },
            { name: 'Jenkins', iconKey: 'jenkins' },
            { name: 'Spinnaker', iconKey: 'spinnaker' },
            { name: 'Prometheus', iconKey: 'prometheus' },
            { name: 'Grafana', iconKey: 'grafana' },
        ],
    },
    {
        key: 'otherTools',
        translationKey: 'portfolio.skills.categories.otherTools',
        skills: [
            { name: 'Cursor', iconKey: 'cursor' },
            { name: 'Claude Code', iconKey: 'claudecode' },
            { name: 'GitHub Copilot', iconKey: 'githubcopilot' },
            { name: 'SOLID', link: 'https://en.wikipedia.org/wiki/SOLID' },
            { name: 'DDD', link: 'https://en.wikipedia.org/wiki/Domain-driven_design' },
            { name: 'Scrum', link: 'https://en.wikipedia.org/wiki/Scrum_(software_development)' },
            { name: 'Kanban', link: 'https://en.wikipedia.org/wiki/Kanban' },
            { name: 'XP', link: 'https://en.wikipedia.org/wiki/Extreme_programming' },
            { name: 'Minimal Modeling', link: 'https://minimalmodeling.com/' },
            { name: 'Zod', iconKey: 'zod' },
            { name: 'Gulp', iconKey: 'gulp' },
            { name: 'Rollup', iconKey: 'rollup' },
            { name: 'Webpack', iconKey: 'webpack' },
            { name: 'Esbuild', iconKey: 'esbuild' },
            { name: 'Vite', iconKey: 'vite' },
            { name: 'Turborepo', iconKey: 'turborepo' },
            { name: 'Oxlint', iconKey: 'oxlint' },
            { name: 'Oxfmt', iconKey: 'oxfmt' },
            { name: 'Prettier', iconKey: 'prettier' },
            { name: 'pnpm', iconKey: 'pnpm' },
            { name: 'npm', iconKey: 'npm' },
            { name: 'Yarn', iconKey: 'yarn' },
            { name: 'Bun', iconKey: 'bun' },
            { name: 'Jira', iconKey: 'jira' },
            { name: 'Trello', iconKey: 'trello' },
            { name: 'Asana', iconKey: 'asana' },
            { name: 'DBeaver', iconKey: 'dbeaver' },
            { name: 'Anaconda', iconKey: 'anaconda' },
            { name: 'NumPy', iconKey: 'numpy' },
            { name: 'Pandas', iconKey: 'pandas' },
            { name: 'Matplotlib', iconKey: 'matplotlib' },
            { name: 'scikit-learn', iconKey: 'scikitlearn' },
            { name: 'Seaborn', iconKey: 'seaborn' },
        ],
    },
];
