name: Setup pnpm + Node
description: Install and cache pnpm + Node dependencies

runs:
    using: composite
    steps:
        - uses: actions/checkout@v4

        - uses: pnpm/action-setup@v4

        - uses: actions/setup-node@v4
          with:
              node-version: 'lts/*'
              cache: 'pnpm'
